version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: leadfi_db
      POSTGRES_USER: patrickvicente
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  # LeadFi Application
  app:
    build: .
    ports:
      - "5000:8080"
    environment:
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=leadfi_db
      - DB_USER=patrickvicente
      - DB_PASSWORD=password
      - PORT=8080
    depends_on:
      - db
    volumes:
      # Mount source for development (hot reload)
      - .:/app
      - /app/venv  # Exclude venv from mount
      - /app/node_modules
      - /app/frontend/node_modules

volumes:
  postgres_data: 