[phases.setup]
nixPkgs = ["nodejs_18", "python310", "python310Packages.pip", "postgresql"]

[phases.install]
cmds = [
    "python3 -m pip install -r requirements.txt",
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    "cd frontend && npm run build",
    "cd .."
]

[start]
cmd = "python run.py" 