[build]
command = "cd frontend && npm install && npm run build && cd .."

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
PORT = "8080"
FLASK_ENV = "production" 