[build]
# Use Dockerfile instead of Nixpacks
builder = "dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
PORT = "8080"
FLASK_ENV = "production" 